# Business 服务配置

[server]
host = "0.0.0.0"
port = 8080

[database]
url = "mysql://root:12345678@localhost:3306/kex"
max_connections = 10

[redis]
url = "redis://:Aq23-hjPwFB3mBDNFp3W1@localhost:6379/0"
pool_size = 10

[log]
level = "info"
