# Market 服务配置

[server]
host = "0.0.0.0"
port = 8084

[database]
url = "mysql://kex:43mn7rryDRWAdwRa@192.168.3.112:3306/kex"
max_connections = 10

[redis]
url = "redis://:Aq23-hjPwFB3mBDNFp3W1@192.168.3.112:6379/0"
pool_size = 10

[log]
level = "info"

[mongodb]
enabled = true
#url = "mongodb://admin:password123@192.168.3.112:27017"
url = "mongodb://192.168.3.112:27017"
database = "kex"
max_pool_size = 30
min_pool_size = 10

[pulsar]
url = "pulsar://192.168.3.112:6650"
enabled = true